### ISSUE TITLE
Error while attempting to build docker image

### ISSUE THREAD

**Issue by urmjs** [sync-or-swim/pyswim#6]
*** maxLoops exceeded.  Something is wrong with --one-file-per-xsd.

*** Failed to process the following element definitions:
    [<XschemaElement name: "NasAircraftType" type: "NasAircraftType">]

**Comment by BryceBeagle** [comment]
Hey @urmjs , sorry for the delayed response. We didn't expect any usage out of this repo! This appears to be a bug in generateDS. I've reached out to the developer there, and in the meantime locked its version in the Dockerfile. Hopefully it should be fixed now.

Also, unless you need to build pyfixm for your own reasons, do note that there's a [release on PyPI](https://pypi.org/project/pyfixm/) that should stay functional.
